name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@bc480c6823a6a6a425217a1f75b581552f2a600d # tag=v2.1.0
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

