name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@7b2d16136a869a33d1193ff665d2df10f993d0fd # tag=v2.0.0
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}
