name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@05de59550ccea9b58da28fd918fc5a0573328639 # v2.10.0
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

