name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@4205107d9049b7946fb0276c564a35afb9804d81 # tag=v1.0.6
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}