name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@9e562e3e6a29fafcfd3e0ad1c21e3db9146fde48 # tag=v1.0.8
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}