name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@aa08dc4b97008eafd33fa593024663ef59693e71 # v2.7.0
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

