name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@21218e61b841c17ddd74dace7413b3c73a854592 # v2.8.0
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

