name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@2d8703b6d944155b82b5b3031305479e0375ea77 # tag=v2.0.2
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

