name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@9dabd0167c407847daf71746b9ba09a3bedcb357 # tag=v2.0.1
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

