name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@456495897f1124879a3700ef25e55673ae689fad # tag=v1.0.5
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}