name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write 
  actions: write
  pull-requests: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@3d2e2bbbfb76e15d51348dae21130662658d5e36 # tag=v1.0.12
    secrets:
      not_github_token: ${{secrets.WAPWAGNER_TOKEN}}
