name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@7a8c48d526143c8b058cd97476f7fcea16deb674 # v2.9.0
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

