name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@e9d11ae973459fff5e4bef93625449c05904b8f9 # tag=v2.0.3
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

