name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@004a11d0b52f514d9907b4c8ddfd814414bb316e # v2.4.0
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

