name: Build
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: write
  id-token: write

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/build.yaml@2a16746b8008eac282ed6d7ac824388c668ea6ba # tag=v2.1.1
    secrets:
      token: ${{secrets.GITHUB_TOKEN}}

